services:
  finance-postgres:
    image: 'postgres:latest'
    environment:
      - DB_SERVER=finance-postgres
      - POSTGRES_DB=financial_app
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_LOG=debug
    volumes:
      - finance-data:/var/lib/postgresql/data
      - ./src/main/resources:/liquibase
    ports:
      - 5432:5432

  financial-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SERVER=finance-postgres
      - POSTGRES_DB=financial_app
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 8080:8080
    links:
      - finance-postgres

volumes:
  finance-data: