services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  spring-boot-app:
    image: jasokolowska/financial-app-image
    ports:
      - "8080:8080"
#    environment:
      # ...
    depends_on:
      - postgres
