server:
  port: 8080
  forward-headers-strategy: framework
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false
    use-root-path: true
  cache:
    disabled: true