server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/financial_app
    username: root
    password: admin
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

