springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false
    use-root-path: true
    url: /api-docs/openapi.yaml
  cache:
    disabled: true
  api-docs:
    enabled: false
server:
  port: 8080
  forward-headers-strategy: framework